--https://www.postgresql.org/docs/current/datatype-character.html
CREATE TABLE IF NOT EXISTS E_MAIN_REQ(
    ID_MAIN_REQ VARCHAR PRIMARY KEY,
    VA_NAME VARCHAR,
    VA_USR VARCHAR,
    DH_DBT TIMESTAMP(3),
    DH_FIN TIMESTAMP(3),
    LNCH VARCHAR,
    LOC VARCHAR,
    VA_CMPLT CHAR,
    VA_THRED VARCHAR,
    VA_APP_NME VARCHAR,
    VA_VRS VARCHAR,
    VA_ADRS VARCHAR,
    VA_ENV VARCHAR,
    VA_OS VARCHAR,
    VA_RE VARCHAR
);

CREATE TABLE IF NOT EXISTS E_IN_REQ (
    ID_IN_REQ VARCHAR PRIMARY KEY,
    VA_MTH VARCHAR,
    VA_PRTCL VARCHAR,
    VA_HST VARCHAR,
    CD_PRT INT,
    VA_PTH VARCHAR,
    VA_QRY VARCHAR,
    VA_CNT_TYP VARCHAR,
    VA_AUTH VARCHAR,
    CD_STT INT,
    VA_I_SZE BIGINT,
    VA_O_SZE BIGINT,
    DH_DBT TIMESTAMP(3),
    DH_FIN TIMESTAMP(3),
    VA_THRED VARCHAR,
    VA_API_NME VARCHAR,
    VA_USR VARCHAR,
    VA_APP_NME VARCHAR,
    VA_VRS VARCHAR,
    VA_ADRS VARCHAR,
    VA_ENV VARCHAR,
    VA_OS VARCHAR,
    VA_RE VARCHAR
);

CREATE TABLE IF NOT EXISTS E_OUT_REQ (
    ID_OUT_REQ VARCHAR PRIMARY KEY,
    VA_MTH VARCHAR,
    VA_PRTCL VARCHAR,
    VA_HST VARCHAR,
    CD_PRT INT,
    VA_PTH VARCHAR,
    VA_QRY VARCHAR,
    VA_CNT_TYP VARCHAR,
    VA_AUTH VARCHAR,
    CD_STT INT,
    VA_I_SZE BIGINT,
    VA_O_SZE BIGINT,
    DH_DBT TIMESTAMP(3),
    DH_FIN TIMESTAMP(3),
    VA_THRED VARCHAR,
    CD_IN_REQ VARCHAR
);

CREATE TABLE IF NOT EXISTS E_OUT_QRY (
    ID_OUT_QRY BIGINT,
    VA_HST VARCHAR,
    CD_PRT INT,
    VA_SCHMA VARCHAR,
    DH_DBT TIMESTAMP(3),
    DH_FIN TIMESTAMP(3), -- NULLABLE
    VA_USR VARCHAR,
    VA_THRED VARCHAR,
    VA_DRV VARCHAR,
    VA_DB_NME VARCHAR,
    VA_DB_VRS VARCHAR,
    VA_CMPLT CHAR,
    CD_IN_REQ VARCHAR
);

CREATE TABLE IF NOT EXISTS E_DB_ACT(
    VA_TYP VARCHAR,
    DH_DBT TIMESTAMP(3),
    DH_FIN TIMESTAMP(3), -- NULLABLE
    VA_CMPLT  CHAR,
    CD_OUT_QRY BIGINT
);
