ALTER TABLE E_ENV_INS add IF NOT EXISTS VA_BRCH VARCHAR;
ALTER TABLE E_ENV_INS add IF NOT EXISTS VA_HSH VARCHAR;
ALTER TABLE E_ENV_INS add IF NOT EXISTS DH_END TIMESTAMP(6);
ALTER TABLE E_DTB_STG add IF NOT EXISTS VA_CMD VARCHAR;
ALTER TABLE E_LCL_RQT add IF NOT EXISTS VA_TYP VARCHAR;