CREATE TABLE E_IN_REQ (
    UUID varchar(36) PRIMARY KEY,
    LB_CNT_TYPE  VARCHAR(255) NOT NULL,
    VA_APP  VARCHAR(255) NOT NULL ,
    VA_ACT  VARCHAR(255 )NOT NULL ,
    VA_RES  VARCHAR(255) NOT NULL ,
    VA_PRINCIPAL VARCHAR(255) NOT NULL
);

CREATE TABLE E_OUT_REQ (
    UUID varchar(36) PRIMARY KEY,
    VA_URL VARCHAR(255) NOT NULL,
    VA_MTH VARCHAR(10) NOT NULL ,
    CD_STT INT NOT NULL,
    DH_DBT TIMESTAMP NOT NULL,
    DH_FIN TIMESTAMP NOT NULL,
    CD_IN_REQ INT,
    FOREIGN KEY (CD_IN_REQ) REFERENCES E_IN_REQ(UUID)
);

CREATE TABLE E_OUT_QRY (
    UUID varchar(36) PRIMARY KEY,
    DH_DBT TIMESTAMP NOT NULL,
    DH_FIN TIMESTAMP NOT NULL,
    CD_IN_REQ INT,
    FOREIGN KEY (CD_IN_REQ) REFERENCES E_IN_REQ(UUID)
);

CREATE TABLE  E_DATA_ACT(
    id INT AUTO_INCREMENT PRIMARY KEY,
    VA_TYPE VARCHAR(255) NOT NULL,
    DH_DBT TIMESTAMP NOT NULL,
    DH_FIN TIMESTAMP NOT NULL,
    VA_FAIL  BOOLEAN NOT NULL,
    CD_OUT_REQ INT,
    FOREIGN KEY (CD_OUT_REQ) REFERENCES E_OUT_REQ(UUID)
);

